FROM ghcr.io/triboelectric/statick:debug

LABEL "name"="Statick Action"
LABEL "version"="0.12.0"
LABEL "repository"="https://github.com/triboelectric/statick.git"
LABEL "homepage"="https://github.com/triboelectric/statick"
LABEL "maintainer"="Thomas Denewiler <tdenewiler@gmail.com>"

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
