---
name: Statick

on: # NOLINT
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Statick
        uses: ./action
        with:
          profile: self_check.yaml
          timings: true
          user_paths: /github/workspace/src/statick_tool
